language: nodejs
node_js:
  - 12
  - 10
  - node

os: 
  - osx
  - windows
  - linux
dist: xenial  

before_script:
  - npm install
  - npm run build

script:
  - npm run test

notifications:
  email: false