apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-line-api
  labels:
    app: story-line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-line
  template:
    metadata:
      labels:
        app: story-line
    spec:
      containers:
        - name: story-line-api
          image: docker.pkg.github.com/assapir/story-line/story-line-api:latest
          ports:
            - containerPort: 1337
          envFrom:
            - secretRef: 
                name: jwt-secret
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: story-line
  name: story-line-api
spec:
  type: ExternalName
  externalName: story-line-api.com
